version: '3'

services:
  finalproject:
    build:
      context: ./finalProject  # Spring Boot 서버 경로
    ports:
      - "9988:9988"  # BE 서버 포트
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # 프로덕션 프로파일 활성화 (선택사항)
    networks:
      - app-network
    volumes:
      - ../server-upload:/upload
    depends_on:
      - mysql-db
    restart: unless-stopped

  home:
    build:
      context: ./home  # React + Node.js 서버 경로
    ports:
      - "3000:3000"  # FE 서버 포트
    networks:
      - app-network
    restart: unless-stopped

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 5678  # MySQL root 비밀번호
      MYSQL_DATABASE: shopping   # 사용할 DB 이름
    ports:
      - "3306:3306"  # MySQL 포트
    volumes:
      - ../mysql-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    depends_on:
      - finalproject
      - home
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email hackey1318@naver.com --agree-tos --no-eff-email -d cinemate.shop -d www.cinemate.shop

networks:
  app-network:
    driver: bridge
