# 필수 events 블록 추가
events {
    worker_connections 1024;  # 기본 설정
}

http {
    # 프론트엔드 서버 설정 (React)
    upstream frontend {
        server home:3000;  # React 서버
    }

    # 백엔드 서버 설정 (Spring Boot)
    upstream backend {
        server finalproject:9988;  # Spring Boot 서버
    }

    server {
        listen 80;
        server_name cinemate.shop www.cinemate.shop;  # 외부 도메인

        # CORS 설정 (프론트엔드에서 오는 요청에 대해 허용)
        add_header Access-Control-Allow-Origin http://localhost:3000;
        add_header Access-Control-Allow-Origin http://192.168.1.252:3000;
        add_header Access-Control-Allow-Origin http://cinemate.shop;
        add_header Access-Control-Allow-Origin http://www.cinemate.shop;
        add_header Access-Control-Allow-Origin http://223.130.159.159;
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, PATCH, OPTIONS';
        add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';
        add_header Access-Control-Allow-Credentials true;
        add_header Access-Control-Expose-Headers 'accessToken, Content-Disposition';

        # 프론트엔드 서버에 대한 요청 처리 (React 애플리케이션)
        location / {
            proxy_pass http://frontend;  # 프론트엔드 React 서버로 프록시
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # API 요청 처리 (Spring Boot 서버로 프록시)
        location /api/ {
            # CORS preflight (OPTIONS) 요청 처리
            if ($request_method = 'OPTIONS') {
                add_header Access-Control-Allow-Origin http://223.130.159.159;
                add_header Access-Control-Allow-Origin http://localhost:3000;
                add_header Access-Control-Allow-Origin http://192.168.1.252:3000;
                add_header Access-Control-Allow-Origin http://cinemate.shop;
                add_header Access-Control-Allow-Origin http://www.cinemate.shop;
                add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, PATCH, OPTIONS';
                add_header Access-Control-Allow-Headers 'Origin, Content-Type, Accept, Authorization';
                add_header Access-Control-Allow-Credentials true;
                add_header Access-Control-Expose-Headers 'accessToken, Content-Disposition';
                return 204;
            }

            # 나머지 API 요청 처리 (Spring Boot 백엔드로 프록시)
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://backend;  # 백엔드 Spring Boot 서버로 프록시
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    }
}
