server {
    listen 80;

    # 프론트엔드 요청을 처리
    location / {
        proxy_pass http://home:3000;  # React + Node.js 서버
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 백엔드 API 요청을 처리
    location /api/ {
        proxy_pass http://finalProject:9988;  # Spring Boot 서버의 포트 9988로 변경
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
