kakao.login.api_key=sdfa
kakao.login.client_secret=asdfaf

# code
kakao.login.redirect_uri=http://localhost:8080/oauth/kakao/code
kakao.login.uri.code=/oauth/authorize
kakao.login.uri.base=https://kauth.kakao.com

# get token
kakao.login.uri.token=/oauth/token

# login
kakao.api.uri.base=https://kapi.kakao.com
kakao.api.uri.user=/v2/user/me